import { TemplateKey, TemplateMetadata } from './templateTypes';

export const defaultTemplateKey: TemplateKey = 'minimal_business';

export const templateMetadata: Record<TemplateKey, TemplateMetadata> = {
  restaurant_classic: {
    key: 'restaurant_classic',
    displayName: 'Restaurant Free',
    description: 'A simple food-business layout for menus, contact details, and opening hours.',
    industry: 'Food & Beverage',
    category: 'Restaurant',
    rendererKey: 'restaurant',
    previewImage: 'restaurant_classic.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['WARTEG', 'RESTAURANT'],
    status: 'active',
    catalogStatus: 'available',
    catalogVisibility: 'modal',
    previewHighlights: ['Menu-first layout', 'WhatsApp and directions CTA', 'Classic restaurant sections'],
    capabilities: { formattedOpeningHours: true },
  },
  restaurant_premium: {
    key: 'restaurant_premium',
    displayName: 'Restaurant Premium',
    description: 'Premium restaurant landing page with chef story, signature dishes, and reservation-focused conversion.',
    industry: 'Food & Beverage',
    category: 'Restaurant',
    rendererKey: 'restaurant_premium',
    previewImage: 'restaurant-premium.jpg',
    tier: 'premium',
    recommendedBusinessTypes: ['RESTAURANT', 'WARTEG', 'CAFE'],
    status: 'active',
    catalogStatus: 'locked',
    catalogVisibility: 'primary',
    previewHighlights: ['Premium hero and reservation flow', 'Signature menu sections', 'Full menu modal with item detail'],
    capabilities: { heroSlideshow: true, premiumMenuModal: true, galleryBatchUpload: true, menuItemDetail: true, formattedOpeningHours: true },
    supportsHeroSlideshow: true,
  },
  restaurant_luxury: {
    key: 'restaurant_luxury',
    displayName: 'Restaurant Luxury',
    description: 'Luxury restaurant template for high-end dining and hospitality brands.',
    industry: 'Food & Beverage',
    category: 'Restaurant',
    rendererKey: 'restaurant',
    previewImage: 'restaurant_luxury.jpg',
    tier: 'luxury',
    recommendedBusinessTypes: ['RESTAURANT', 'CAFE'],
    status: 'planned',
    catalogStatus: 'coming_soon',
    catalogVisibility: 'hidden',
    previewHighlights: ['Luxury editorial direction', 'High-end dining copy', 'Future premium commerce track'],
  },
  laundry_clean: {
    key: 'laundry_clean',
    displayName: 'Laundry Free',
    description: 'A clean service layout for laundry pricing, contact, and location details.',
    industry: 'Local Services',
    category: 'Laundry',
    rendererKey: 'laundry',
    previewImage: 'laundry_clean.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['LAUNDRY'],
    status: 'active',
    catalogStatus: 'available',
    catalogVisibility: 'modal',
    previewHighlights: ['Service pricing layout', 'Pickup contact CTA', 'Laundry-focused proof sections'],
    capabilities: { formattedOpeningHours: true },
  },
  cafe_minimal: {
    key: 'cafe_minimal',
    displayName: 'Cafe Minimal',
    description: 'Minimal cafe template for simple menu, atmosphere, and contact presentation.',
    industry: 'Food & Beverage',
    category: 'Cafe',
    rendererKey: 'generic_business',
    previewImage: 'cafe_minimal.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['CAFE'],
    status: 'planned',
    catalogStatus: 'coming_soon',
    catalogVisibility: 'hidden',
    previewHighlights: ['Simple cafe profile', 'Basic menu and visit details', 'Future classic cafe option'],
  },
  cafe_modern: {
    key: 'cafe_modern',
    displayName: 'Cafe Free',
    description: 'A simple cafe layout for drinks, menu items, and store information.',
    industry: 'Food & Beverage',
    category: 'Cafe',
    rendererKey: 'cafe',
    previewImage: 'cafe-modern.jpg',
    tier: 'premium',
    recommendedBusinessTypes: ['CAFE'],
    status: 'active',
    catalogStatus: 'available',
    catalogVisibility: 'modal',
    previewHighlights: ['Modern cafe landing page', 'Lifestyle story sections', 'Classic public CTA structure'],
    capabilities: { formattedOpeningHours: true },
  },
  cafe_premium: {
    key: 'cafe_premium',
    displayName: 'Cafe Premium',
    description: 'Premium cafe template with brand story, signature menu, visit planning, and contact-focused conversion.',
    industry: 'Food & Beverage',
    category: 'Cafe',
    rendererKey: 'cafe_premium',
    previewImage: 'cafe-premium.jpg',
    tier: 'premium',
    recommendedBusinessTypes: ['CAFE'],
    status: 'active',
    catalogStatus: 'locked',
    catalogVisibility: 'modal',
    previewHighlights: ['Premium cafe hero and menu-first flow', 'Coffee & Bites modal with item detail', 'Warm ambience and placeholder treatment'],
    capabilities: { heroSlideshow: true, premiumMenuModal: true, galleryBatchUpload: true, menuItemDetail: true, formattedOpeningHours: true },
    supportsHeroSlideshow: true,
  },
  clinic_professional: {
    key: 'clinic_professional',
    displayName: 'Clinic Free',
    description: 'A simple professional layout for clinic information, schedule, and contact details.',
    industry: 'Healthcare',
    category: 'Clinic',
    rendererKey: 'clinic',
    previewImage: 'clinic-professional.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['CLINIC'],
    status: 'active',
    catalogStatus: 'available',
    catalogVisibility: 'modal',
    previewHighlights: ['Clinic service structure', 'Trust and contact sections', 'Appointment-oriented layout'],
    capabilities: { formattedOpeningHours: true },
  },
  corporate_executive: {
    key: 'corporate_executive',
    displayName: 'Corporate Free',
    description: 'A simple company profile layout for services, credibility, and contact information.',
    industry: 'Business Services',
    category: 'Corporate',
    rendererKey: 'corporate',
    previewImage: 'corporate-executive.jpg',
    tier: 'premium',
    recommendedBusinessTypes: ['CLINIC', 'LOCAL_SERVICE', 'RETAIL'],
    status: 'active',
    catalogStatus: 'available',
    catalogVisibility: 'modal',
    previewHighlights: ['Executive business presentation', 'Trust-led service sections', 'Professional contact flow'],
    capabilities: { formattedOpeningHours: true },
  },
  minimal_business: {
    key: 'minimal_business',
    displayName: 'Business Free',
    description: 'A flexible starter layout for general UMKM websites.',
    industry: 'Local Services',
    category: 'General Business',
    rendererKey: 'generic_business',
    previewImage: 'minimal_business.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['LAUNDRY', 'WORKSHOP', 'SALON', 'RETAIL', 'LOCAL_SERVICE'],
    status: 'active',
    catalogStatus: 'available',
    catalogVisibility: 'modal',
    previewHighlights: ['Flexible business profile', 'Services and contact sections', 'Safe fallback layout'],
    capabilities: { formattedOpeningHours: true },
  },
};

export const legacyTemplateNameAliases: Record<string, TemplateKey> = {
  restaurant_default: 'restaurant_classic',
  restaurant_demo_template: 'restaurant_classic',
  warteg_default: 'restaurant_classic',
  warteg_demo_template: 'restaurant_classic',
  laundry_default: 'laundry_clean',
  laundry_demo_template: 'laundry_clean',
  workshop_default: 'minimal_business',
  workshop_demo_template: 'minimal_business',
  clinic_default: 'clinic_professional',
  clinic_demo_template: 'clinic_professional',
  cafe_default: 'cafe_modern',
  cafe_demo_template: 'cafe_modern',
  salon_default: 'minimal_business',
  retail_default: 'minimal_business',
  local_service_default: 'corporate_executive',
};

export function isTemplateKey(value?: string | null): value is TemplateKey {
  return Boolean(value && value in templateMetadata);
}
