import { TemplateKey, TemplateMetadata } from './templateTypes';

export const defaultTemplateKey: TemplateKey = 'minimal_business';

export const templateMetadata: Record<TemplateKey, TemplateMetadata> = {
  restaurant_classic: {
    key: 'restaurant_classic',
    displayName: 'Restaurant Classic',
    description: 'Clean restaurant landing page optimized for food businesses.',
    industry: 'Food & Beverage',
    category: 'Restaurant',
    rendererKey: 'restaurant',
    previewImage: 'restaurant_classic.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['WARTEG', 'RESTAURANT'],
    status: 'active',
  },
  restaurant_premium: {
    key: 'restaurant_premium',
    displayName: 'Restaurant Premium',
    description: 'Premium restaurant landing page with chef story, signature dishes, and reservation-focused conversion.',
    industry: 'Food & Beverage',
    category: 'Restaurant',
    rendererKey: 'restaurant_premium',
    previewImage: 'restaurant-premium.jpg',
    tier: 'premium',
    recommendedBusinessTypes: ['RESTAURANT', 'WARTEG', 'CAFE'],
    status: 'active',
    supportsHeroSlideshow: true,
  },
  restaurant_luxury: {
    key: 'restaurant_luxury',
    displayName: 'Restaurant Luxury',
    description: 'Luxury restaurant template for high-end dining and hospitality brands.',
    industry: 'Food & Beverage',
    category: 'Restaurant',
    rendererKey: 'restaurant',
    previewImage: 'restaurant_luxury.jpg',
    tier: 'luxury',
    recommendedBusinessTypes: ['RESTAURANT', 'CAFE'],
    status: 'planned',
  },
  laundry_clean: {
    key: 'laundry_clean',
    displayName: 'Laundry Clean',
    description: 'Clean service landing page designed for laundry pickup, pricing, and contact flows.',
    industry: 'Local Services',
    category: 'Laundry',
    rendererKey: 'laundry',
    previewImage: 'laundry_clean.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['LAUNDRY'],
    status: 'active',
  },
  cafe_minimal: {
    key: 'cafe_minimal',
    displayName: 'Cafe Minimal',
    description: 'Minimal cafe template for simple menu, atmosphere, and contact presentation.',
    industry: 'Food & Beverage',
    category: 'Cafe',
    rendererKey: 'generic_business',
    previewImage: 'cafe_minimal.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['CAFE'],
    status: 'planned',
  },
  cafe_modern: {
    key: 'cafe_modern',
    displayName: 'Cafe Modern',
    description: 'Modern cafe template for lifestyle-focused cafes and coffee shops.',
    industry: 'Food & Beverage',
    category: 'Cafe',
    rendererKey: 'cafe',
    previewImage: 'cafe-modern.jpg',
    tier: 'premium',
    recommendedBusinessTypes: ['CAFE'],
    status: 'active',
  },
  cafe_premium: {
    key: 'cafe_premium',
    displayName: 'Cafe Premium',
    description: 'Premium cafe template with brand story, signature menu, visit planning, and contact-focused conversion.',
    industry: 'Food & Beverage',
    category: 'Cafe',
    rendererKey: 'cafe_premium',
    previewImage: 'cafe-premium.jpg',
    tier: 'premium',
    recommendedBusinessTypes: ['CAFE'],
    status: 'active',
    supportsHeroSlideshow: true,
  },
  clinic_professional: {
    key: 'clinic_professional',
    displayName: 'Clinic Professional',
    description: 'Professional healthcare landing page designed for clinics and medical practices.',
    industry: 'Healthcare',
    category: 'Clinic',
    rendererKey: 'clinic',
    previewImage: 'clinic-professional.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['CLINIC'],
    status: 'active',
  },
  corporate_executive: {
    key: 'corporate_executive',
    displayName: 'Corporate Executive',
    description: 'Executive business template for corporate, professional service, and consulting websites.',
    industry: 'Business Services',
    category: 'Corporate',
    rendererKey: 'corporate',
    previewImage: 'corporate-executive.jpg',
    tier: 'premium',
    recommendedBusinessTypes: ['CLINIC', 'LOCAL_SERVICE', 'RETAIL'],
    status: 'active',
  },
  minimal_business: {
    key: 'minimal_business',
    displayName: 'Minimal Business',
    description: 'Fallback business template for local services that need clear profile, service, and contact sections.',
    industry: 'Local Services',
    category: 'General Business',
    rendererKey: 'generic_business',
    previewImage: 'minimal_business.jpg',
    tier: 'standard',
    recommendedBusinessTypes: ['LAUNDRY', 'WORKSHOP', 'SALON', 'RETAIL', 'LOCAL_SERVICE'],
    status: 'active',
  },
};

export const legacyTemplateNameAliases: Record<string, TemplateKey> = {
  restaurant_default: 'restaurant_classic',
  restaurant_demo_template: 'restaurant_classic',
  warteg_default: 'restaurant_classic',
  warteg_demo_template: 'restaurant_classic',
  laundry_default: 'laundry_clean',
  laundry_demo_template: 'laundry_clean',
  workshop_default: 'minimal_business',
  workshop_demo_template: 'minimal_business',
  clinic_default: 'clinic_professional',
  clinic_demo_template: 'clinic_professional',
  cafe_default: 'cafe_modern',
  cafe_demo_template: 'cafe_modern',
  salon_default: 'minimal_business',
  retail_default: 'minimal_business',
  local_service_default: 'corporate_executive',
};

export function isTemplateKey(value?: string | null): value is TemplateKey {
  return Boolean(value && value in templateMetadata);
}
